name: CI/CD Pipeline

on:
  push:
    branches:
      - '**' # This will match all branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Create known_hosts
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts

    - name: Add server to known hosts
      run: ssh-keyscan 60.204.251.220 >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        sshpass -p ${{ secrets.SERVER_PASSWORD }} rsync -r . root@60.204.251.220:/tmp/html
        sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh root@60.204.251.220 "docker cp /tmp/html blog:/usr/share/nginx && docker restart blog"
